# site
title: Lou
baseurl: ""
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Lou
desc: >
  A Jekyll theme (that looks awesome). Lou is free, lightweight,
  and customizable as a blog, archive, or portfolio.

# posts
newest_first: true
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# build settings
markdown: kramdown
theme: lou
exclude:
  - Gemfile
  - Gemfile.lock