# site
title: Lou
baseurl: ""
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
author: Lillian Chen
email: your-email@domain.com
description: >
  Lily is currently a developer at IBM Watson Health based in Cambridge,
  Massachusetts. She recently graduated from Cornell studying computer
  science. Check out her blog or Twitter if you're curious. Reach out if
  you're feeling something more.

# build settings
markdown: kramdown
theme: lou
exclude:
  - Gemfile
  - Gemfile.lock